//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolkerKinzel.CsvTools.Mappings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolkerKinzel.CsvTools.Mappings.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier is not well-formed..
        /// </summary>
        internal static string BadIdentifier {
            get {
                return ResourceManager.GetString("BadIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast null to {0}..
        /// </summary>
        internal static string CannotCastNull {
            get {
                return ResourceManager.GetString("CannotCastNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the CSV data as {0}..
        /// </summary>
        internal static string CannotParseCsv {
            get {
                return ResourceManager.GetString("CannotParseCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DefaultValue of the TypeConverter MUST be null..
        /// </summary>
        internal static string DefaultValueNotNull {
            get {
                return ResourceManager.GetString("DefaultValueNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The separator must not be an empty string..
        /// </summary>
        internal static string EmptySeparator {
            get {
                return ResourceManager.GetString("EmptySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format string is not supported: {0}..
        /// </summary>
        internal static string FormatStringNotSupported {
            get {
                return ResourceManager.GetString("FormatStringNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri does not have the required type..
        /// </summary>
        internal static string IncorrectUriType {
            get {
                return ResourceManager.GetString("IncorrectUriType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null..
        /// </summary>
        internal static string InstanceIsNull {
            get {
                return ResourceManager.GetString("InstanceIsNull", resourceCulture);
            }
        }
    }
}
